version: '3'

services:
  web: 
    build: ./web
    volumes:
      - ./testwork:/var/www/html
    ports:
      - 8080:80
  db:
    image: mysql
    restart: always
    environment:
    - MYSQL_ROOT_PASSWORD=1234
    - MYSQL_DATABASE:data
    - MYSQL_USER:root  
  adminer:
    image: adminer
    restart: always
    ports:
      - 6080:80
  composer:
    image: composer:1.6
    volumes:
        - ./testwork:/var/www/html
    command: composer install